[project]
name = "horus"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Philipp Rosenfeld", email = "Rosenfeld.Philipp@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "moderngl>=5.12.0",
    "numpy>=2.4.6",
    "pillow>=12.3.0",
    "prompt-toolkit>=3.0.53",
    "pyglet>=2.1.16",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
]

[project.scripts]
horus = "horus:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
python_files = ["test_*.py", "tests_*.py"]
addopts = "--cov=src/horus --cov-report=term-missing --cov-report=html"

[tool.coverage.run]
source = ["src/horus"]

[tool.coverage.html]
directory = "htmlcov"
